# Generated by Django 3.2.13 on 2023-09-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idolos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('jogos', models.CharField(max_length=10)),
                ('posicao', models.CharField(choices=[('P', 'Ponta'), ('L', 'Lateral'), ('M', 'Meia')], max_length=1)),
                ('estado', models.CharField(choices=[('V', 'Vivo'), ('F', 'Falecido')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=20)),
                ('pontos', models.IntegerField()),
                ('partidas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=20)),
                ('artilheiro', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=50)),
            ],
        ),
    ]
