# Generated by Django 3.2.13 on 2023-09-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabela',
        ),
    ]
