# Generated by Django 3.2.13 on 2023-09-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_tabela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('games', models.IntegerField()),
                ('position', models.CharField(choices=[('G', 'Goleiro'), ('Z', 'Zagueiro'), ('L', 'Lateral'), ('V', 'Volante'), ('M', 'Meia'), ('P', 'Ponta'), ('A', 'Atacante')], max_length=1)),
                ('age', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('scorer', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Idolos',
        ),
        migrations.DeleteModel(
            name='Titulos',
        ),
    ]
